language: objective-c

before_install:
  - brew install rbenv ruby-build
  - echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile
  - source ~/.bash_profile
  - rbenv install 2.4.0
  - rbenv global 2.4.0
  - ruby -v
  - sudo gem install xcpretty
  - sudo gem install bundler
  - sudo gem install cocoapods
  - bundle install
  - bundle exec pod keys set MMMCrashlyticsAPIKey "-"
  - bundle exec pod keys set MMMNotificationsAPIKey "-"
  - bundle exec pod install

branches:
  only:
  - master

xcode_workspace: MacMagazine.xcworkspace
xcode_scheme: MacMagazine

osx_image: xcode8.2
xcode_sdk: iphonesimulator9.3

script:
  - xcodebuild test -workspace MacMagazine.xcworkspace -scheme 'MacMagazine' -sdk iphonesimulator | xcpretty -c && exit ${PIPESTATUS[0]}
