language: objective-c

before_install:
  - sudo gem install xcpretty
  - gem install bundler
  - bundle install
  - bundle exec pod install

branches:
  only:
  - master

xcode_workspace: MacMagazine.xcworkspace
xcode_scheme: MacMagazine

osx_image: xcode8.2
xcode_sdk: iphonesimulator9.3

script:
  - xcodebuild -workspace MacMagazine.xcworkspace -scheme 'MacMagazine' -sdk iphonesimulator build | xcpretty -c && exit ${PIPESTATUS[0]}
